name: hallomobil
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  provider: ^6.1.5
  http: ^1.3.0
  google_sign_in: ^6.3.0
  video_player: ^2.10.0
  country_flags: ^3.2.0
  video_player_platform_interface: ^6.3.0
  audioplayers: ^6.5.0
  flutter_tts: ^4.2.3
  speech_to_text: ^7.1.0
  shared_preferences: ^2.5.3
  chewie: ^1.12.1
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  flutter_pdfview: ^1.4.1+1
  path_provider: ^2.1.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "assets/logo/logo.png"
  adaptive_icon_foreground: "assets/logo/logo.png"

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/videos/
    - assets/images/
    - assets/sounds/correct.wav
    - assets/sounds/incorrect.mp3

